# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from ui.main import main
from examples.baidu_index_best_practice import save_sql, get_search_index_demo

if __name__ == '__main__':
    with open('file/关键词.txt', 'r', encoding='utf') as f:
        keywords = f.readlines()

    keywords_list = keywords
    keywords_list = [i.replace('\n', '') for i in keywords_list]
    keywords_list = [i.split(',') for i in keywords_list]

    # save_sql(get_search_index_demo(keywords_list))

    main()
