# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt6 import QtCore, QtWidgets
from PyQt6 import QtWebEngineWidgets
from PyQt6.QtWidgets import QPushButton
from qt_material import apply_stylesheet


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.webEngineView = QtWebEngineWidgets.QWebEngineView(parent=self.centralwidget)
        self.webEngineView.setGeometry(QtCore.QRect(130, 0, 910, 600))
        self.webEngineView.setUrl(QtCore.QUrl("file:///../html/lineChartsCurrent.html"))
        self.webEngineView.setObjectName("webEngineView")

        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 131, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.pushButton_1 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_1.setObjectName("pushButton")
        self.pushButton_1.clicked.connect(self.on_button_1_clicked)
        self.verticalLayout.addWidget(self.pushButton_1)

        self.pushButton_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_5")
        self.pushButton_2.clicked.connect(self.on_button_2_clicked)
        self.verticalLayout.addWidget(self.pushButton_2)

        self.pushButton_3 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_2")
        self.pushButton_3.clicked.connect(self.on_button_3_clicked)
        self.verticalLayout.addWidget(self.pushButton_3)

        self.pushButton_4 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_3")
        self.pushButton_4.clicked.connect(self.on_button_4_clicked)
        self.verticalLayout.addWidget(self.pushButton_4)

        self.pushButton_5 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_3")
        self.pushButton_5.clicked.connect(self.on_button_5_clicked)
        self.verticalLayout.addWidget(self.pushButton_5)

        self.pushButton_6 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_3")
        self.pushButton_6.clicked.connect(self.on_button_6_clicked)
        self.verticalLayout.addWidget(self.pushButton_6)

        self.pushButton_7 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_3")
        self.pushButton_7.clicked.connect(self.on_button_7_clicked)
        self.verticalLayout.addWidget(self.pushButton_7)

        # 添加一个刷新的按钮，这个按钮点击后会刷新所有的子元素
        self.button = QPushButton("Refresh")
        self.button.clicked.connect(self.webEngineView.reload)
        self.verticalLayout.addWidget(self.button)

        self.pushButton_8 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_3")
        self.pushButton_8.clicked.connect(self.on_button_8_clicked)
        self.verticalLayout.addWidget(self.pushButton_8)



        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主页"))
        self.pushButton_1.setText(_translate("MainWindow", "搜索指数"))
        self.pushButton_2.setText(_translate("MainWindow", "需求图谱——领域"))
        self.pushButton_3.setText(_translate("MainWindow", "人群分布——地区"))
        self.pushButton_4.setText(_translate("MainWindow", "词云统计"))
        self.pushButton_5.setText(_translate("MainWindow", "需求图谱——性别"))
        self.pushButton_6.setText(_translate("MainWindow", "需求图谱——年龄"))
        self.pushButton_7.setText(_translate("MainWindow", "需求——领域"))
        self.pushButton_8.setText(_translate("MainWindow", "资讯指数"))

    def on_button_1_clicked(self):
        self.webEngineView.setUrl(QtCore.QUrl("file:///../html/lineChartsCurrent.html"))

    def on_button_2_clicked(self):
        self.webEngineView.setUrl(QtCore.QUrl("file:///../html/BarCharts.html"))

    def on_button_3_clicked(self):
        self.webEngineView.setUrl(QtCore.QUrl("file:///../html/MapCharts.html"))

    def on_button_4_clicked(self):
        self.webEngineView.setUrl(QtCore.QUrl("file:///../html/wordCloudCharts.html"))

    def on_button_5_clicked(self):
        self.webEngineView.setUrl(QtCore.QUrl("file:///../html/PieCharts.html"))
    def on_button_6_clicked(self):
        self.webEngineView.setUrl(QtCore.QUrl("file:///../html/BarAgeCharts.html"))

    def on_button_7_clicked(self):
        self.webEngineView.setUrl(QtCore.QUrl("file:///../html/RadarCharts.html"))
    def on_button_8_clicked(self):
        self.webEngineView.setUrl(QtCore.QUrl("file:///../html/AQICharts.html"))



def main():
    app = QtWidgets.QApplication(sys.argv)
    apply_stylesheet(app, theme='dark_teal.xml')
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
